version: '2'

services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    environment:
      - ZERQU_CONF=/code/local_config.py
    command: python manage.py runserver -h 0.0.0.0
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=development
      - PGDATA=/data
    volumes:
      - ./data/:/code

  redis:
    image: redis:3.2
